Repository TomographicImaging/CIL, pull requests merged in 2022-06, with the labels that each got.

#1274 Limit pydata-sphinx-theme version
  docs/docs_environment.yml
Labels: Waiting for review

#1276 show_geometry update for matplotlib
  CHANGELOG.md
  Wrappers/Python/cil/utilities/display.py
  recipe/meta.yaml
Labels: Waiting for review

#1101 Added TXRMDatareader Functionality
  Wrappers/Python/cil/io/TXRMDataReader.py
  Wrappers/Python/cil/io/ZEISSDataReader.py
  Wrappers/Python/cil/io/__init__.py
Labels: high_priority

#1280 Ensure documentation is built from CIL master
  .github/workflows/conda_and_docs_build.yml
  CHANGELOG.md
  docs/docs_environment.yml
Labels: Waiting for review

#1267 Add ndim property for DataContainer
  CHANGELOG.md
  Wrappers/Python/cil/framework/framework.py
  Wrappers/Python/test/test_DataContainer.py
Labels: Merge pending jenkins

#1273 Merge CIL-ASTRA in to CIL
  CHANGELOG.md
  README.md
  Wrappers/Python/CMake/setup.py.in
  Wrappers/Python/cil/optimisation/operators/Operator.py
  Wrappers/Python/cil/plugins/astra/__init__.py
  Wrappers/Python/cil/plugins/astra/operators/AstraProjector2D.py
  Wrappers/Python/cil/plugins/astra/operators/AstraProjector3D.py
  Wrappers/Python/cil/plugins/astra/operators/ProjectionOperator.py
  Wrappers/Python/cil/plugins/astra/operators/__init__.py
  Wrappers/Python/cil/plugins/astra/processors/AstraBackProjector2D.py
  Wrappers/Python/cil/plugins/astra/processors/AstraBackProjector3D.py
  Wrappers/Python/cil/plugins/astra/processors/AstraForwardProjector2D.py
  Wrappers/Python/cil/plugins/astra/processors/AstraForwardProjector3D.py
  Wrappers/Python/cil/plugins/astra/processors/FBP.py
  Wrappers/Python/cil/plugins/astra/processors/FBP_Flexible.py
  Wrappers/Python/cil/plugins/astra/processors/FDK_Flexible.py
  Wrappers/Python/cil/plugins/astra/processors/__init__.py
  Wrappers/Python/cil/plugins/astra/utilities/__init__.py
  Wrappers/Python/cil/plugins/astra/utilities/convert_geometry_to_astra.py
  Wrappers/Python/cil/plugins/astra/utilities/convert_geometry_to_astra_vec_2D.py
  Wrappers/Python/cil/plugins/astra/utilities/convert_geometry_to_astra_vec_3D.py
  Wrappers/Python/test/test_PluginsAstra_FBP.py
  Wrappers/Python/test/test_PluginsAstra_GPU.py
  Wrappers/Python/test/test_PluginsAstra_Geometry.py
  Wrappers/Python/test/test_PluginsAstra_ProjectorConsistency.py
  Wrappers/Python/test/test_PluginsAstra_Projectors.py
  docs/docs_environment.yml
  docs/source/plugins.rst
  recipe/conda_build_config.yaml
  recipe/meta.yaml
Labels: Waiting for review
