Repository TomographicImaging/CIL, pull requests merged in 2022-04, with the labels that each got.

#1215 PR Template
  .github/PULL_REQUEST_TEMPLATE.MD
Labels: Waiting for review

#1193 Projector tests
  Wrappers/Python/cil/plugins/tigre/Geometry.py
  Wrappers/Python/cil/plugins/tigre/ProjectionOperator.py
  Wrappers/Python/test/test_PluginsAstra_CPU.py
  Wrappers/Python/test/test_PluginsAstra_FBP.py
  Wrappers/Python/test/test_PluginsAstra_GPU.py
  Wrappers/Python/test/test_PluginsTigre_FBP.py
  Wrappers/Python/test/test_PluginsTigre_General.py
  Wrappers/Python/test/test_PluginsTigre_Siddon.py
  Wrappers/Python/test/test_PluginsTigre_interpolated.py
  Wrappers/Python/test/utils_projectors.py
  recipe/meta.yaml
Labels: Merge pending jenkins

#1212 add link to articles.
  CITATION.cff
  README.md
  docs/source/index.rst
Labels: Work In Progress, Waiting for review

#1219 reviewed doc
  docs/source/index.rst
Labels: Work In Progress

#1197 change prints to logging
  Wrappers/Python/cil/optimisation/operators/GradientOperator.py
Labels: Merge pending jenkins

#1206 Optimisation of MixedL21Norm
  Wrappers/Python/cil/optimisation/functions/MixedL21Norm.py
  Wrappers/Python/test/test_functions.py
  recipe/meta.yaml
Labels: Merge pending jenkins

#1163 Fix_SIRT
  Wrappers/Python/cil/optimisation/algorithms/PDHG.py
  Wrappers/Python/cil/optimisation/algorithms/SIRT.py
  Wrappers/Python/test/test_algorithms.py
  docs/source/optimisation.rst
  docs/source/refs.bib
Labels: Merge pending jenkins

#1223 Fix cgls initial
  CHANGELOG.md
  Wrappers/Python/cil/optimisation/algorithms/CGLS.py
  Wrappers/Python/test/test_algorithms.py
Labels: Merge pending jenkins

#1224 Mask operator with domain parameter
  Wrappers/Python/cil/optimisation/operators/DiagonalOperator.py
  Wrappers/Python/cil/optimisation/operators/MaskOperator.py
Labels: Waiting for review

#1227 Fix install step
  CHANGELOG.md
  Wrappers/Python/CMakeLists.txt
Labels: Waiting for review

#1228 Simplify version number
  CHANGELOG.md
  CMakeLists.txt
  Wrappers/Python/CMake/parse_git_describe.py
  Wrappers/Python/CMake/setup.py.in
  Wrappers/Python/CMake/version.py.in
  Wrappers/Python/cil/__init__.py
  Wrappers/Python/test/test_version.py
  recipe/meta.yaml
Labels: Waiting for review
