Repository TomographicImaging/CIL, pull requests merged in 2023-12, with the labels that each got.

#1529 Fix1542
  CHANGELOG.md
  Wrappers/Python/cil/optimisation/functions/MixedL21Norm.py
  Wrappers/Python/test/test_functions.py
Labels: Waiting for review

#1539 Fix bug with show2D and 3D DataContainers
  CHANGELOG.md
  Wrappers/Python/cil/framework/framework.py
  Wrappers/Python/cil/utilities/display.py
  Wrappers/Python/test/test_DataContainer.py
Labels: Waiting for review

#1556 Updated documentation for L2normSquared and LeastSquares functions
  CHANGELOG.md
  Wrappers/Python/cil/optimisation/functions/Function.py
  Wrappers/Python/cil/optimisation/functions/L2NormSquared.py
  Wrappers/Python/cil/optimisation/functions/LeastSquares.py
  docs/source/optimisation.rst
Labels: Merge pending jenkins

#1607 Update conda_and_docs_build.yml
  .github/workflows/conda_and_docs_build.yml
Labels: Waiting for review, gh-actions

#1618 Adds WeightedL1Norm to Functions
  CHANGELOG.md
  NOTICE.txt
  Wrappers/Python/cil/optimisation/functions/L1Norm.py
  Wrappers/Python/cil/optimisation/functions/__init__.py
  Wrappers/Python/test/test_functions.py
  docs/source/optimisation.rst
Labels: enhancement, Waiting for review

#1634 CI: update docs & tidy workflow
  .github/workflows/README.md
  .github/workflows/build.yml
Labels: bug, Waiting for review, gh-actions

#1611 Documentation for compositionoperator and sumoperator
  CHANGELOG.md
  Wrappers/Python/cil/optimisation/operators/Operator.py
  docs/source/optimisation.rst
Labels: Merge pending jenkins

#1610 Update documentation for symmetrised gradient
  CHANGELOG.md
  Wrappers/Python/cil/optimisation/operators/SymmetrisedGradientOperator.py
Labels: Merge pending jenkins

#1582 Adjoint of DiagonalOperator for complex values
  CHANGELOG.md
  Wrappers/Python/cil/optimisation/operators/DiagonalOperator.py
  Wrappers/Python/test/test_Operator.py
Labels: Merge pending jenkins

#1580 Changed ISTA and FISTA so that g can be None
  CHANGELOG.md
  Wrappers/Python/cil/optimisation/algorithms/FISTA.py
  Wrappers/Python/test/test_ISTA_algorithm.py
  Wrappers/Python/test/test_algorithms.py
  docs/source/refs.bib
Labels: Waiting for review

#1633 CI: add docker images
  .github/workflows/README.md
  .github/workflows/build.yml
  CHANGELOG.md
  Dockerfile
  README.md
  scripts/requirements-test.yml
Labels: enhancement, Waiting for review, gh-actions

#1635 installation docs
  README.md
Labels: enhancement, Waiting for review
