Repository TomographicImaging/CIL, pull requests merged in 2023-11, with the labels that each got.

#1513 BlockOperator: added a function to return a list of norms and the ability to set this list of norms
  CHANGELOG.md
  Wrappers/Python/cil/optimisation/operators/BlockOperator.py
  Wrappers/Python/cil/optimisation/operators/Operator.py
  Wrappers/Python/test/test_BlockOperator.py
  Wrappers/Python/test/test_Operator.py
Labels: Waiting for review, Merge pending jenkins

#1515 Data container reductions
  CHANGELOG.md
  NOTICE.txt
  Wrappers/Python/cil/framework/framework.py
  Wrappers/Python/test/test_DataContainer.py
  Wrappers/Python/test/test_functions.py
Labels: Waiting for review, Merge pending jenkins

#1557 Make the direct method in BlockOperator clearer with a variable name change
  CHANGELOG.md
  Wrappers/Python/cil/optimisation/operators/BlockOperator.py
Labels: Merge pending jenkins

#1583 ipp 2021.10 build fix
  CHANGELOG.md
  recipe/build.sh
  recipe/meta.yaml
  scripts/requirements-test.yml
  src/Core/Binning.cpp
  src/Core/include/FBP_filtering.h
Labels: bug, Waiting for review

#1517 readme: slight tidy
  README.md
Labels: Waiting for review

#1589 fix borken whitespace
  .github/PULL_REQUEST_TEMPLATE.MD
Labels: bug, Waiting for review

#1558 Iterator in BlockDatacontainer
  CHANGELOG.md
  Wrappers/Python/cil/framework/BlockDataContainer.py
  Wrappers/Python/test/test_BlockDataContainer.py
Labels: Merge pending jenkins
