Repository TomographicImaging/CIL, pull requests merged in 2024-05, with the labels that each got.

#1743 ProjectionMap operator bug fix in adjoint and added documentation
  CHANGELOG.md
  Wrappers/Python/cil/optimisation/operators/ProjectionMap.py
  Wrappers/Python/test/test_Operator.py
  docs/source/optimisation.rst
Labels: Merge pending jenkins

#1797 docs: fix version switcher
  .github/workflows/build.yml
  docs/docs_environment.yml
  docs/mkversions.py
  docs/source/conf.py
Labels: bug, Waiting for review, documentation

#1742 Return when out is specified for operators and functions
  CHANGELOG.md
  Wrappers/Python/cil/framework/BlockDataContainer.py
  Wrappers/Python/cil/framework/framework.py
  Wrappers/Python/cil/optimisation/functions/BlockFunction.py
  Wrappers/Python/cil/optimisation/functions/Function.py
  Wrappers/Python/cil/optimisation/functions/IndicatorBox.py
  Wrappers/Python/cil/optimisation/functions/KullbackLeibler.py
  Wrappers/Python/cil/optimisation/functions/L1Norm.py
  Wrappers/Python/cil/optimisation/functions/L2NormSquared.py
  Wrappers/Python/cil/optimisation/functions/LeastSquares.py
  Wrappers/Python/cil/optimisation/functions/MixedL21Norm.py
  Wrappers/Python/cil/optimisation/functions/OperatorCompositionFunction.py
  Wrappers/Python/cil/optimisation/functions/Rosenbrock.py
  Wrappers/Python/cil/optimisation/functions/TotalVariation.py
  Wrappers/Python/cil/optimisation/operators/BlockOperator.py
  Wrappers/Python/cil/optimisation/operators/BlurringOperator.py
  Wrappers/Python/cil/optimisation/operators/ChannelwiseOperator.py
  Wrappers/Python/cil/optimisation/operators/DiagonalOperator.py
  Wrappers/Python/cil/optimisation/operators/FiniteDifferenceOperator.py
  Wrappers/Python/cil/optimisation/operators/GradientOperator.py
  Wrappers/Python/cil/optimisation/operators/IdentityOperator.py
  Wrappers/Python/cil/optimisation/operators/MatrixOperator.py
  Wrappers/Python/cil/optimisation/operators/Operator.py
  Wrappers/Python/cil/optimisation/operators/ProjectionMap.py
  Wrappers/Python/cil/optimisation/operators/SymmetrisedGradientOperator.py
  Wrappers/Python/cil/optimisation/operators/ZeroOperator.py
  Wrappers/Python/test/test_out_in_place.py
  Wrappers/Python/test/testclass.py
Labels: Waiting for review

#1802 Direct method of BlockOperator returns a single DataContainer if the output shape is (1,1)
  CHANGELOG.md
  Wrappers/Python/cil/optimisation/operators/BlockOperator.py
  Wrappers/Python/test/test_BlockOperator.py
  Wrappers/Python/test/test_Operator.py
Labels: bug, Waiting for review

#1799 Add BlockDataContainer geometry and pnorm fixes
  CHANGELOG.md
  Wrappers/Python/cil/framework/BlockGeometry.py
  Wrappers/Python/cil/framework/__init__.py
  Wrappers/Python/cil/framework/block.py
  Wrappers/Python/cil/framework/framework.py
  Wrappers/Python/cil/plugins/astra/operators/ProjectionOperator.py
  Wrappers/Python/cil/plugins/tigre/ProjectionOperator.py
  Wrappers/Python/test/test_BlockDataContainer.py
  Wrappers/Python/test/test_functions.py
Labels: Waiting for review

#1807 Removed checks for blurring operator to allow SIRFDataContainers to be passed
  CHANGELOG.md
  Wrappers/Python/cil/optimisation/operators/BlurringOperator.py
Labels: Merge pending jenkins

#1808 Added __neg__ to function class
  CHANGELOG.md
  Wrappers/Python/cil/optimisation/functions/Function.py
  Wrappers/Python/test/test_functions.py
Labels: enhancement, Waiting for review
