Repository TomographicImaging/CIL, pull requests merged in 2024-03, with the labels that each got.

#1741 issue templates: add CIL version
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/enhancement.md
Labels: Waiting for review, documentation

#1726 Soft shrinkage in place bug fix
  CHANGELOG.md
  Wrappers/Python/cil/optimisation/functions/L1Norm.py
Labels: bug, Waiting for review

#1733 build: clean cmake commands
  .github/workflows/build.yml
  README.md
  docs/source/developer_guide.rst
  recipe/bld.bat
Labels: Waiting for review

#1677 Improve CIL citation information
  CITATION.cff
  NOTICE.txt
  README.md
Labels: Waiting for review

#1749 fix import warning & docs missing GPU deps
  .github/workflows/build.yml
  Wrappers/Python/cil/utilities/jupyter/__init__.py
Labels: bug, Waiting for review, gh-actions, documentation

#1748 CI: pass tests in ignore-paths
  .github/workflows/build.yml
  .github/workflows/skip.yml
Labels: Waiting for review, gh-actions

#1712 Download data in dataexamples
  CHANGELOG.md
  Wrappers/Python/cil/utilities/dataexample.py
  Wrappers/Python/test/test_dataexample.py
  Wrappers/Python/test/test_io.py
Labels: Waiting for review

#1750 fix broken citation link
  CITATION.cff
Labels: bug, Waiting for review, documentation

#1753 Update __add__ of Function.py to accept SIRF functions
  Wrappers/Python/cil/optimisation/functions/Function.py
Labels: Waiting for review

#1751 docs: callback examples, fix some cross-refs
  docs/source/framework.rst
  docs/source/optimisation.rst
Labels: Waiting for review, documentation

#1729 CI: CUDA tests
  .github/workflows/README.md
  .github/workflows/build.yml
  README.md
  Wrappers/Python/test/test_DataProcessor.py
  Wrappers/Python/test/test_PluginsAstra_GPU.py
  Wrappers/Python/test/test_PluginsAstra_Projectors.py
  Wrappers/Python/test/test_PluginsTigre_FBP.py
  Wrappers/Python/test/test_PluginsTigre_General.py
  Wrappers/Python/test/test_PluginsTigre_Siddon.py
  Wrappers/Python/test/test_PluginsTigre_interpolated.py
  Wrappers/Python/test/test_functions.py
  Wrappers/Python/test/test_reconstructors.py
  Wrappers/Python/test/utils.py
  scripts/requirements-test.yml
Labels: enhancement, Waiting for review, gh-actions

#1550 ApproximateGradientSumFunction class and example SGFunction for Stochastic Gradient Descent
  CHANGELOG.md
  NOTICE.txt
  Wrappers/Python/cil/optimisation/functions/ApproximateGradientSumFunction.py
  Wrappers/Python/cil/optimisation/functions/Function.py
  Wrappers/Python/cil/optimisation/functions/SGFunction.py
  Wrappers/Python/cil/optimisation/functions/__init__.py
  Wrappers/Python/test/test_approximate_gradient.py
  docs/source/optimisation.rst
Labels: Waiting for review

#1763 Skip tests on windows
  Wrappers/Python/test/test_dataexample.py
Labels: bug, Waiting for review, gh-actions

#1767 CI: fix concurrent CUDA runners
  .github/workflows/build.yml
Labels: bug, Waiting for review, gh-actions
