Repository TomographicImaging/CIL, pull requests merged in 2024-06, with the labels that each got.

#1816 website: improve widgets
  docs/docs_environment.yml
  docs/pages/_layouts/frontpage.html
  docs/pages/index.md
Labels: Waiting for review, documentation

#1826 FGP_TV: Change default non negativity to False
  CHANGELOG.md
  Wrappers/Python/cil/plugins/ccpi_regularisation/functions/regularisers.py
Labels: Waiting for review

#1667 Add plot filter method
  CHANGELOG.md
  Wrappers/Python/cil/recon/FBP.py
  Wrappers/Python/test/test_plots/filters/cosine_0.png
  Wrappers/Python/test/test_plots/filters/cosine_1.png
  Wrappers/Python/test/test_plots/filters/custom_0.png
  Wrappers/Python/test/test_plots/filters/custom_1.png
  Wrappers/Python/test/test_plots/filters/hamming_0.png
  Wrappers/Python/test/test_plots/filters/hamming_1.png
  Wrappers/Python/test/test_plots/filters/hann_0.png
  Wrappers/Python/test/test_plots/filters/hann_1.png
  Wrappers/Python/test/test_plots/filters/ram-lak_0.png
  Wrappers/Python/test/test_plots/filters/ram-lak_1.png
  Wrappers/Python/test/test_plots/filters/shepp-logan_0.png
  Wrappers/Python/test/test_plots/filters/shepp-logan_1.png
  Wrappers/Python/test/test_reconstructors.py
Labels: enhancement

#1841 fix numpy>=2 bytes
  Wrappers/Python/cil/io/NEXUSDataReader.py
  Wrappers/Python/cil/io/NEXUSDataWriter.py
Labels: bug, high_priority, Waiting for review

#1851 allow Algorithm.run(np.inf)
  Wrappers/Python/cil/optimisation/algorithms/Algorithm.py
Labels: enhancement, Waiting for review
