Repository TomographicImaging/CIL, pull requests merged in 2024-01, with the labels that each got.

#1641 remove unused env
  Wrappers/Python/environment.yml
Labels: Waiting for review

#1614 Quality metrics have added mask option
  CHANGELOG.md
  Wrappers/Python/cil/utilities/quality_measures.py
  Wrappers/Python/test/test_quality_measures.py
Labels: Waiting for review

#1636 Update norm of Composition operator
  CHANGELOG.md
  Wrappers/Python/cil/optimisation/operators/Operator.py
  Wrappers/Python/test/test_Operator.py
Labels: bug, Waiting for review

#1651 Catch warning in quality metrics
  Wrappers/Python/cil/utilities/quality_measures.py
  Wrappers/Python/test/test_quality_measures.py
Labels: Merge pending jenkins

#1642 Stochastic sampler only
  CHANGELOG.md
  Wrappers/Python/CMake/setup.py.in
  Wrappers/Python/cil/optimisation/utilities/__init__.py
  Wrappers/Python/cil/optimisation/utilities/sampler.py
  Wrappers/Python/test/test_sampler.py
  docs/source/optimisation.rst
Labels: Merge pending jenkins
