Repository TomographicImaging/CIL, pull requests merged in 2024-04, with the labels that each got.

#1769 fix logging
  Wrappers/Python/cil/framework/framework.py
  Wrappers/Python/cil/io/RAWFileWriter.py
  Wrappers/Python/cil/io/TIFF.py
  Wrappers/Python/cil/io/ZEISSDataReader.py
  Wrappers/Python/cil/io/utilities.py
  Wrappers/Python/cil/optimisation/algorithms/ADMM.py
  Wrappers/Python/cil/optimisation/algorithms/CGLS.py
  Wrappers/Python/cil/optimisation/algorithms/FISTA.py
  Wrappers/Python/cil/optimisation/algorithms/GD.py
  Wrappers/Python/cil/optimisation/algorithms/PDHG.py
  Wrappers/Python/cil/optimisation/algorithms/SIRT.py
  Wrappers/Python/cil/optimisation/algorithms/SPDHG.py
  Wrappers/Python/cil/optimisation/functions/IndicatorBox.py
  Wrappers/Python/cil/optimisation/functions/KullbackLeibler.py
  Wrappers/Python/cil/optimisation/functions/TotalVariation.py
  Wrappers/Python/cil/optimisation/operators/GradientOperator.py
  Wrappers/Python/cil/optimisation/operators/Operator.py
  Wrappers/Python/cil/plugins/astra/operators/ProjectionOperator.py
  Wrappers/Python/cil/plugins/astra/processors/FBP.py
  Wrappers/Python/cil/plugins/astra/processors/FBP_Flexible.py
  Wrappers/Python/cil/plugins/tigre/FBP.py
  Wrappers/Python/cil/plugins/tigre/ProjectionOperator.py
  Wrappers/Python/cil/processors/CofR_image_sharpness.py
  Wrappers/Python/cil/processors/CofR_xcorrelation.py
  Wrappers/Python/cil/processors/Slicer.py
  Wrappers/Python/test/test_BlockOperator.py
  Wrappers/Python/test/test_DataContainer.py
  Wrappers/Python/test/test_Gradient.py
  Wrappers/Python/test/test_Operator.py
  Wrappers/Python/test/test_TranslateFunction.py
  Wrappers/Python/test/test_algorithms.py
  Wrappers/Python/test/test_functions.py
  Wrappers/Python/test/test_io.py
Labels: bug, enhancement, Waiting for review

#1771 CI: force cleanup on setup fail
  .github/workflows/build.yml
Labels: bug, Waiting for review, gh-actions

#1747 Deprecation of code for v24
  CHANGELOG.md
  Wrappers/Python/cil/io/ZEISSDataReader.py
  Wrappers/Python/cil/io/__init__.py
  Wrappers/Python/cil/optimisation/functions/TotalVariation.py
  Wrappers/Python/cil/plugins/astra/processors/FBP.py
  Wrappers/Python/cil/plugins/tigre/FBP.py
  Wrappers/Python/cil/plugins/tigre/ProjectionOperator.py
  Wrappers/Python/cil/processors/CentreOfRotationCorrector.py
  Wrappers/Python/cil/processors/CofR_image_sharpness.py
  Wrappers/Python/test/test_functions.py
  Wrappers/Python/test/test_io.py
Labels: Waiting for review

#1770 Suppress prints from Tigre fdk
  Wrappers/Python/cil/plugins/tigre/FBP.py
Labels: Waiting for review

#1776 Small bug fixes to SGD documentation
  NOTICE.txt
  Wrappers/Python/cil/optimisation/functions/ApproximateGradientSumFunction.py
  Wrappers/Python/cil/optimisation/functions/SGFunction.py
  docs/source/optimisation.rst
Labels: Waiting for review

#1772 Update list of CIL developers
  CITATION.cff
  NOTICE.txt
Labels: Waiting for review

#1778 bump everything
  .github/workflows/README.md
  .github/workflows/build.yml
  CHANGELOG.md
  Dockerfile
  README.md
  Wrappers/Python/cil/plugins/ccpi_regularisation/functions/regularisers.py
  Wrappers/Python/cil/plugins/tigre/FBP.py
  Wrappers/Python/test/test_DataProcessor.py
  Wrappers/Python/test/test_PluginsRegularisation.py
  Wrappers/Python/test/test_algorithms.py
  Wrappers/Python/test/test_functions.py
  Wrappers/Python/test/test_io.py
  Wrappers/Python/test/test_subset.py
  Wrappers/Python/test/utils.py
  recipe/conda_build_config.yaml
  recipe/meta.yaml
  scripts/create_local_env_for_cil_development.sh
  scripts/requirements-test.yml
Labels: high_priority, Waiting for review

#1779 docker: bump jupyter-server-proxy
  Dockerfile
Labels: enhancement, high_priority, Waiting for review

#1791 docker: bump base image
  .github/workflows/build.yml
  Dockerfile
  recipe/build.sh
  scripts/create_local_env_for_cil_development.sh
  scripts/requirements-test.yml
Labels: enhancement, Waiting for review

#1792 build: correct version even if unannotated tag
  .github/workflows/build.yml
  Wrappers/Python/CMake/parse_git_describe.py
Labels: bug, high_priority, Waiting for review

#1789 GD stored loss bug
  CHANGELOG.md
  Wrappers/Python/cil/optimisation/algorithms/GD.py
  Wrappers/Python/test/test_algorithms.py
Labels: Merge pending jenkins

#1615 Adds WaveletOperator, WaveletNorm
  CHANGELOG.md
  Wrappers/Python/cil/optimisation/functions/L1Norm.py
  Wrappers/Python/cil/optimisation/functions/L1Sparsity.py
  Wrappers/Python/cil/optimisation/functions/__init__.py
  Wrappers/Python/cil/optimisation/operators/IdentityOperator.py
  Wrappers/Python/cil/optimisation/operators/Operator.py
  Wrappers/Python/cil/optimisation/operators/WaveletOperator.py
  Wrappers/Python/cil/optimisation/operators/__init__.py
  Wrappers/Python/test/test_Operator.py
  Wrappers/Python/test/test_functions.py
  Wrappers/Python/test/test_out_in_place.py
  Wrappers/Python/test/test_wavelets.py
  docs/source/optimisation.rst
Labels: Merge pending jenkins
