Repository TomographicImaging/CIL, pull requests merged in 2024-09, with the labels that each got.

#1924 future-proof `find_package(Python)` again
  CMakeLists.txt
  Wrappers/Python/CMakeLists.txt
Labels: bug, SIRF/CIL integration, high_priority, gh-actions

#1919 Update ImageData and AcquisitionData equality checks
  CHANGELOG.md
  Wrappers/Python/cil/framework/acquisition_data.py
  Wrappers/Python/cil/framework/acquisition_geometry.py
  Wrappers/Python/cil/framework/image_data.py
  Wrappers/Python/test/test_AcquisitionGeometry.py
  Wrappers/Python/test/test_DataContainer.py
Labels: Waiting for review

#1930 Update README.md to add ipykernel to instructions
  README.md
Labels: Waiting for review

#1935 CI: fix mamba
  .github/workflows/build.yml
Labels: bug, high_priority, Waiting for review, gh-actions
