Repository TomographicImaging/CIL, pull requests merged in 2024-07, with the labels that each got.

#1866 conda: use upstream intel channel
  .github/workflows/build.yml
  Dockerfile
  README.md
  docs/docs_environment.yml
  scripts/create_local_env_for_cil_development.sh
  scripts/requirements-test.yml
Labels: bug, high_priority, Waiting for review, Merge pending jenkins, gh-actions

#1828 Added partitioner documentation
  CHANGELOG.md
  docs/source/framework.rst
Labels: Merge pending jenkins

#1868 Regularisation toolkit 24.0.1
  CHANGELOG.md
  Wrappers/Python/cil/plugins/ccpi_regularisation/functions/regularisers.py
  Wrappers/Python/test/test_PluginsRegularisation.py
  recipe/meta.yaml
  scripts/create_local_env_for_cil_development.sh
  scripts/requirements-test.yml
Labels: Merge pending jenkins

#1624 SAG and SAGA approximate gradient methods
  Wrappers/Python/cil/optimisation/functions/ApproximateGradientSumFunction.py
  Wrappers/Python/cil/optimisation/functions/SAGFunction.py
  Wrappers/Python/cil/optimisation/functions/__init__.py
  Wrappers/Python/test/test_approximate_gradient.py
  Wrappers/Python/test/test_sampler.py
  docs/source/optimisation.rst
  scripts/requirements-test.yml
Labels: Waiting for review

#1874 fix numba implementation of KullbackLeibler
  CHANGELOG.md
  Wrappers/Python/cil/optimisation/functions/KullbackLeibler.py
Labels: Waiting for review
