Repository TomographicImaging/CIL, pull requests merged in 2024-02, with the labels that each got.

#1648 Functions use sapyb and improved documentation in function base class and simple functions
  CHANGELOG.md
  Wrappers/Python/cil/optimisation/functions/Function.py
Labels: Merge pending jenkins

#1590 tidy dev scripts
  README.md
  docs/docs_environment.yml
  recipe/build.sh
  recipe/meta.yaml
  scripts/create_local_env_for_cil_development.sh
  scripts/create_local_env_for_cil_development_tests.sh
Labels: Waiting for review

#1661 test docker images
  .github/workflows/build.yml
  CHANGELOG.md
Labels: bug, Merge pending jenkins, gh-actions

#1674 GHA: free disk space for docker build
  .github/workflows/build.yml
Labels: bug, Waiting for review, gh-actions

#1671 Added reference to the stochastic sampler
  Wrappers/Python/cil/optimisation/utilities/sampler.py
Labels: Waiting for review

#1540 fix KL njit and gradient numba without mask
  CHANGELOG.md
  Wrappers/Python/cil/optimisation/functions/KullbackLeibler.py
  Wrappers/Python/test/test_function_KullbackLeibler.py
Labels: bug, Waiting for review

#1670 Allow slice list to be set as tuple in show1D
  CHANGELOG.md
  Wrappers/Python/cil/utilities/display.py
Labels: Waiting for review

#1678 add .gitignore
  .gitignore
Labels: enhancement, good first issue, Waiting for review

#1679 docs: native build, update sphinx, add versioning
  .github/workflows/build.yml
  docs/docs_environment.yml
  docs/mkversions.py
  docs/source/conf.py
  scripts/requirements-test.yml
Labels: enhancement, Waiting for review, gh-actions, documentation

#1675 docker: better run instructions
  Dockerfile
  README.md
Labels: Waiting for review, documentation

#1702 RelWithDebInfo
  .github/workflows/build.yml
  CMakeLists.txt
  Dockerfile
  Wrappers/Python/CMakeLists.txt
  recipe/bld.bat
  recipe/build.sh
  src/Core/CMakeLists.txt
Labels: enhancement, Waiting for review

#1659 `Algorithm.run(callbacks: list[Callback])`
  CHANGELOG.md
  Wrappers/Python/cil/optimisation/algorithms/Algorithm.py
  Wrappers/Python/cil/optimisation/algorithms/CGLS.py
  Wrappers/Python/cil/optimisation/algorithms/GD.py
  Wrappers/Python/cil/optimisation/algorithms/PDHG.py
  Wrappers/Python/cil/optimisation/utilities/callbacks.py
  Wrappers/Python/test/test_algorithms.py
  docs/source/optimisation.rst
Labels: enhancement, Waiting for review

#1709 set CMake CP0148 policy
  CHANGELOG.md
  CMakeLists.txt
Labels: Waiting for review

#1711 Fixes issue TestQualityMeasures' object has no attribute 'id_coins_sliced' #1710
  Wrappers/Python/test/test_quality_measures.py
Labels: bug, Waiting for review

#1715 fix py3.8 typehints
  Wrappers/Python/cil/optimisation/algorithms/Algorithm.py
Labels: bug, high_priority, Waiting for review, Merge pending jenkins

#1717 tests: fix windows tempfile race
  Wrappers/Python/test/test_algorithms.py
Labels: bug, Waiting for review, Merge pending jenkins

#1664 New unit tests for operator and functions to test the `out` functionality and in place calculations
  CHANGELOG.md
  Wrappers/Python/cil/optimisation/functions/Function.py
  Wrappers/Python/cil/optimisation/functions/IndicatorBox.py
  Wrappers/Python/cil/optimisation/functions/KullbackLeibler.py
  Wrappers/Python/cil/optimisation/functions/L1Norm.py
  Wrappers/Python/cil/optimisation/functions/TotalVariation.py
  Wrappers/Python/cil/optimisation/operators/FiniteDifferenceOperator.py
  Wrappers/Python/cil/utilities/errors.py
  Wrappers/Python/test/test_Operator.py
  Wrappers/Python/test/test_functions.py
  Wrappers/Python/test/test_out_in_place.py
  Wrappers/Python/test/testclass.py
Labels: Waiting for review

#1658 SIRT update objective fix and new TV unit-test
  CHANGELOG.md
  Wrappers/Python/cil/optimisation/algorithms/SIRT.py
  Wrappers/Python/test/test_algorithms.py
Labels: Waiting for review

#1723 docs: mention docker tags
  README.md
Labels: Waiting for review, documentation

#1727 fix docs licence comments in header
  docs/source/developer_guide.rst
  docs/source/framework.rst
  docs/source/index.rst
  docs/source/introduction.rst
  docs/source/io.rst
  docs/source/optimisation.rst
  docs/source/plugins.rst
  docs/source/processors.rst
  docs/source/recon.rst
  docs/source/refs.bib
  docs/source/utilities.rst
Labels: bug, documentation

#1532 Allow integer or boolean mask to be passed to Masker
  CHANGELOG.md
  Wrappers/Python/cil/processors/CentreOfRotationCorrector.py
  Wrappers/Python/cil/processors/Masker.py
  Wrappers/Python/cil/processors/Normaliser.py
  Wrappers/Python/test/test_DataProcessor.py
Labels: Waiting for review

#1690 Doc render jupyter
  .github/workflows/build.yml
  CMakeLists.txt
  docs/.gitignore
  docs/demos-template.rst
  docs/docs_environment.yml
  docs/mkdemos.py
  docs/source/conf.py
  docs/source/developer_guide.rst
  docs/source/framework.rst
  docs/source/index.rst
Labels: Waiting for review, documentation

#1730 docker: fix missing astra
  Dockerfile
Labels: bug, Waiting for review

#1736 fix imports
  CHANGELOG.md
  Wrappers/Python/cil/plugins/ccpi_regularisation/functions/regularisers.py
  Wrappers/Python/cil/processors/CofR_image_sharpness.py
  Wrappers/Python/cil/recon/FBP.py
  Wrappers/Python/cil/recon/Reconstructor.py
  Wrappers/Python/cil/utilities/jupyter/__init__.py
Labels: bug, SIRF/CIL integration, high_priority, Waiting for review

#1735 remove unneeded file
  _config.yml
Labels: Waiting for review
