Repository TomographicImaging/CIL, pull requests merged in 2024-08, with the labels that each got.

#1858 SumFunction: allow single function input
  CHANGELOG.md
  Wrappers/Python/cil/optimisation/functions/Function.py
  Wrappers/Python/test/test_SumFunction.py
  Wrappers/Python/test/test_approximate_gradient.py
Labels: bug, enhancement, Waiting for review

#1876 migrate to `pyproject.toml`
  .gitignore
  CHANGELOG.md
  CMakeLists.txt
  Wrappers/Python/CMake/parse_git_describe.py
  Wrappers/Python/CMake/setup.py.in
  Wrappers/Python/CMake/sp_dir.py
  Wrappers/Python/CMake/version.py.in
  Wrappers/Python/CMakeLists.txt
  Wrappers/Python/test/test_version.py
  pyproject.toml
  recipe/bld.bat
  recipe/build.sh
  recipe/meta.yaml
Labels: bug, enhancement, high_priority, Waiting for review

#1855 Fixed BlockFunction gradient out and the unit test
  Wrappers/Python/cil/optimisation/functions/BlockFunction.py
  Wrappers/Python/test/test_out_in_place.py
Labels: Waiting for review

#1625 SVRG and LSVRG approximate gradient methods
  CHANGELOG.md
  Wrappers/Python/cil/optimisation/functions/SVRGFunction.py
  Wrappers/Python/cil/optimisation/functions/__init__.py
  Wrappers/Python/test/test_approximate_gradient.py
  docs/source/optimisation.rst
Labels: Waiting for review

#1887 Make Binner accept accelerated=False
  CHANGELOG.md
  Wrappers/Python/cil/processors/Binner.py
  Wrappers/Python/test/test_DataProcessor.py
Labels: Waiting for review

#1885 Remove empty dimensions from DataContainer array
  .gitignore
  CHANGELOG.md
  Wrappers/Python/cil/framework/framework.py
  Wrappers/Python/test/test_BlockDataContainer.py
  Wrappers/Python/test/test_DataContainer.py
  Wrappers/Python/test/utils_projectors.py
Labels: bug, Waiting for review

#1842 find_package(Python)
  CMakeLists.txt
  Wrappers/Python/CMakeLists.txt
Labels: bug, high_priority, Waiting for review

#1896 tests: split & speedup datacontainer binary operations
  Wrappers/Python/test/test_DataContainer.py
Labels: Waiting for review, gh-actions

#1899 Revert "find_package(Python) (#1842)"
  CMakeLists.txt
  Wrappers/Python/CMakeLists.txt
Labels: bug, Waiting for review, Merge pending jenkins

#1805 Unit tests for out argument to processors
  CHANGELOG.md
  Wrappers/Python/cil/framework/framework.py
  Wrappers/Python/cil/plugins/astra/processors/AstraBackProjector2D.py
  Wrappers/Python/cil/plugins/astra/processors/AstraBackProjector3D.py
  Wrappers/Python/cil/plugins/astra/processors/AstraForwardProjector2D.py
  Wrappers/Python/cil/plugins/astra/processors/AstraForwardProjector3D.py
  Wrappers/Python/cil/plugins/astra/processors/FBP.py
  Wrappers/Python/cil/plugins/astra/processors/FBP_Flexible.py
  Wrappers/Python/cil/plugins/astra/processors/FDK_Flexible.py
  Wrappers/Python/cil/plugins/tigre/FBP.py
  Wrappers/Python/cil/processors/Binner.py
  Wrappers/Python/cil/processors/CofR_image_sharpness.py
  Wrappers/Python/cil/processors/CofR_xcorrelation.py
  Wrappers/Python/cil/processors/MaskGenerator.py
  Wrappers/Python/cil/processors/Masker.py
  Wrappers/Python/cil/processors/Normaliser.py
  Wrappers/Python/cil/processors/Padder.py
  Wrappers/Python/cil/processors/PaganinProcessor.py
  Wrappers/Python/cil/processors/RingRemover.py
  Wrappers/Python/cil/processors/Slicer.py
  Wrappers/Python/cil/processors/TransmissionAbsorptionConverter.py
  Wrappers/Python/test/test_DataProcessor.py
  Wrappers/Python/test/test_out_in_place.py
  Wrappers/Python/test/testclass.py
Labels: Waiting for review

#1892 CGLS: deprecate tolerance
  CHANGELOG.md
  Wrappers/Python/cil/optimisation/algorithms/CGLS.py
  Wrappers/Python/cil/optimisation/utilities/callbacks.py
  Wrappers/Python/test/test_algorithms.py
Labels: Merge pending jenkins

#1859 Added BB step size rule to our step size methods
  CHANGELOG.md
  Wrappers/Python/cil/optimisation/utilities/StepSizeMethods.py
  Wrappers/Python/cil/optimisation/utilities/__init__.py
  Wrappers/Python/test/test_stepsizes.py
  docs/source/optimisation.rst
Labels: enhancement, Merge pending jenkins

#1834 add PD3O with tests
  CHANGELOG.md
  Wrappers/Python/cil/optimisation/algorithms/PD3O.py
  Wrappers/Python/cil/optimisation/algorithms/__init__.py
  Wrappers/Python/test/test_algorithms.py
  docs/source/optimisation.rst
Labels: Merge pending jenkins

#1809 Improved documentation layout for algorithm class
  CHANGELOG.md
  Wrappers/Python/cil/optimisation/algorithms/Algorithm.py
Labels: Waiting for review, documentation

#1898 reduce size of SPDHG vs PDHG test data
  CHANGELOG.md
  Wrappers/Python/test/test_algorithms.py
Labels: Waiting for review
