Repository TomographicImaging/CIL, pull requests merged in 2025-04, with the labels that each got.

#2118 add pip required & optional dependencies
  pyproject.toml
Labels: enhancement, SIRF/CIL integration, Waiting for review

#2140 add CODEOWNERS
  .github/CODEOWNERS
Labels: Waiting for review

#2128 Sampler: rename "get_samples" to "view_samples"
  CHANGELOG.md
  Wrappers/Python/cil/optimisation/utilities/sampler.py
  Wrappers/Python/test/test_sampler.py
Labels: Waiting for review

#2144 Update install script to pip install into correct conda env
  CHANGELOG.md
  scripts/create_local_env_for_cil_development.sh
Labels: bug, Waiting for review

#2043 Bug fix to PD3O with stochastic gradient optimisers
  CHANGELOG.md
  Wrappers/Python/cil/optimisation/algorithms/PD3O.py
  Wrappers/Python/cil/optimisation/functions/SVRGFunction.py
  Wrappers/Python/test/test_algorithm_convergence.py
  Wrappers/Python/test/test_algorithms.py
Labels: Waiting for review
