Repository TomographicImaging/CIL, pull requests merged in 2025-05, with the labels that each got.

#2133 Fix argument order for subtract and divide between different container types
  CHANGELOG.md
  Wrappers/Python/cil/framework/data_container.py
  Wrappers/Python/test/test_BlockDataContainer.py
Labels: bug

#2162 data env var
  .github/workflows/build.yml
  Wrappers/Python/cil/utilities/dataexample.py
  Wrappers/Python/test/test_io.py
  docs/source/utilities.rst
Labels: enhancement, discussion, Waiting for review, gh-actions, documentation

#2160 CI: `workflow_dispatch`
  .github/workflows/README.md
  .github/workflows/build.yml
  CHANGELOG.md
  docs/source/developer_guide.rst
Labels: enhancement, Waiting for review, gh-actions
